### ISSUE TITLE
Add proper Python dependencies for pytest-exasol-backend

### ISSUE THREAD

**Issue by ckunki** [exasol/bucketfs-python#153]
Currently, BFSP downloads ITDE from Github, main branch in Gihub workflows [ci-cd.yml](https://github.com/exasol/bucketfs-python/blob/main/.github/workflows/ci-cd.yml#L40), [ci.yml](https://github.com/exasol/bucketfs-python/blob/main/.github/workflows/ci.yml#L40), [pr-merge.yml](https://github.com/exasol/bucketfs-python/blob/main/.github/workflows/pr-merge.yml#L44).

```yaml
- name: Checkout ITDE
  run: git clone https://github.com/exasol/integration-test-docker-environment.git
  working-directory: ..
```
