### ISSUE TITLE
Fix handling of code coverage data

### ISSUE THREAD

**Issue by ckunki** [exasol/bucketfs-python#209]
Implementation of #204 showed some issues with code coverage data. 

The CI build was fixed by appending `|| true` in [report.yml](https://github.com/exasol/bucketfs-python/blob/main/.github/workflows/report.yml#L55) to 

```
poetry run -- coverage report --format markdown >> $GITHUB_STEP_SUMMARY
```

This change should only be required in case the coverage data is empty, which should not be the case for this repository.

**Comment by ckunki** [comment]
Looking at PTB https://github.com/exasol/python-toolbox/ 
### File checks.yml

Writes coverage data to local file `.coverage`
```yml
- name: Run Tests and Collect Coverage
  run: poetry run -- nox -s test:unit -- --coverage
```

Uploads local file .coverage to remote `coverage-python<m>` with `<m>` being the current python version, e.g. 3.9
```yml
- name: Upload Artifacts
    name: coverage-python${{ matrix.python-version }}-fast
        path: .coverage
```
### File report.yml

Combines coverage – but which?
What does coverage-python3.9*/ mean? Potential patch versions of python 3.9?

```yml
- name: Copy Artifacts into Root Folder
  working-directory: ./artifacts
        poetry run -- coverage combine --keep coverage-python3.9*/.coverage
```

### File slow-checks.yml

Uses the same pattern as `checks.yml`.
